"""Pack everything needed to reproduce a result into one zip, and check one later.

A bundle holds the settings, annotations, hand exclusions, prompts, measurements, reports and
model cards, plus a manifest of SHA-256 hashes and the exact package versions used. Masks and
overlays are left out by default (they are regenerated by re-running the analysis) and photos
are optional, because they dominate the size. Every photo's hash is recorded either way, so a
separate image archive can be checked against the bundle.
"""

from __future__ import annotations

import fnmatch
import hashlib
import json
import logging
import platform
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

from fungus_cv.provenance import software_provenance
from fungus_cv.storage import Experiment, iso_utc, utc_now

log = logging.getLogger(__name__)

BUNDLE_FORMAT = 1
MANIFEST_NAME = "manifest.json"
# Results worth keeping: everything except what a re-run recreates from them.
SKIP_RESULT_PARTS = ("masks", "overlays")
EXPERIMENT_FILES = ("config.yaml", "frames.csv", "annotations.json", "exclusions.json",
                    "capture.log", "*prompts*.json")


@dataclass
class ArchiveResult:
    path: Path
    files: int = 0
    bytes_stored: int = 0
    frames_included: int = 0
    frames_recorded: int = 0
    notes: list[str] = field(default_factory=list)


def _packages() -> dict:
    """Versions of every installed package, so the environment can be recreated."""
    from importlib.metadata import distributions

    found = {}
    for dist in distributions():
        name = dist.metadata["Name"]
        if name:
            found[name] = dist.version
    return dict(sorted(found.items(), key=lambda kv: kv[0].lower()))


def environment() -> dict:
    return {
        "python": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "platform": platform.platform(),
        "executable": sys.executable,
        "packages": _packages(),
        **software_provenance(),
    }


class _Bundle:
    """Writes files into the zip, hashing each one for the manifest."""

    def __init__(self, zip_file: zipfile.ZipFile):
        self.zip = zip_file
        self.entries: list[dict] = []

    def add_file(self, source: Path, name: str) -> None:
        data = Path(source).read_bytes()
        self.add_bytes(data, name)

    def add_bytes(self, data: bytes, name: str) -> None:
        if any(e["path"] == name for e in self.entries):
            return
        self.zip.writestr(name, data)
        self.entries.append({"path": name, "bytes": len(data),
                             "sha256": hashlib.sha256(data).hexdigest()})

    def add_text(self, text: str, name: str) -> None:
        self.add_bytes(text.encode("utf-8"), name)


def _matches(name: str, patterns) -> bool:
    return any(fnmatch.fnmatch(name, p) for p in patterns)


def _add_experiment(bundle: _Bundle, experiment: Experiment, prefix: str, frames: bool,
                    masks: bool, weights: bool, result: ArchiveResult) -> dict:
    root = experiment.root
    for path in sorted(root.iterdir()):
        if path.is_file() and _matches(path.name, EXPERIMENT_FILES):
            bundle.add_file(path, f"{prefix}{path.name}")
    results_dir = root / "results"
    for path in sorted(results_dir.rglob("*")) if results_dir.is_dir() else []:
        if not path.is_file():
            continue
        relative = path.relative_to(root)
        kind = relative.parts[1] if len(relative.parts) > 1 else ""
        if "sam2_state" in relative.parts:
            continue  # tracking state belongs to one model version, not to the result
        if not masks and kind in SKIP_RESULT_PARTS:
            continue
        bundle.add_file(path, f"{prefix}{relative.as_posix()}")

    rows = experiment.read_frames()
    frame_rows = []
    for row in rows:
        path = root / row["file"] if row["file"] else None
        digest = row.get("sha256", "")
        if not digest and path is not None and path.exists():
            # Imported photos may have no hash in frames.csv; a bundle always records one.
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
        frame_rows.append({"file": row["file"], "timestamp_utc": row["timestamp_utc"],
                           "sha256": digest, "status": row["status"]})
        if frames and row["status"] == "ok" and path is not None and path.exists():
            bundle.add_file(path, f"{prefix}{row['file']}")
            result.frames_included += 1
    result.frames_recorded += len(frame_rows)
    models = _add_models(bundle, experiment, prefix, weights, result)
    return {"root": str(root), "name": experiment.config.name, "frames": frame_rows,
            "models": models}


def _add_models(bundle: _Bundle, experiment: Experiment, prefix: str, weights: bool,
                result: ArchiveResult) -> list[dict]:
    """Model cards (and optionally weights) of every trained model the settings point at."""
    from fungus_cv.segment.trained import resolve_model_path

    analysis = experiment.config.analysis
    found = []
    for role in ("target", "reference"):
        block = getattr(analysis, role)
        if block.method != "model" or not block.model.path:
            continue
        try:
            model_dir = resolve_model_path(block.model.path, experiment.root)
        except (FileNotFoundError, ValueError) as exc:
            result.notes.append(f"{role} model not found ({exc}); its card is not in the bundle")
            continue
        entry = {"role": role, "path": str(model_dir), "name": model_dir.name}
        card = model_dir / "model.json"
        if card.exists():
            bundle.add_file(card, f"{prefix}models/{model_dir.name}/model.json")
        weights_file = model_dir / "model.pt"
        if weights_file.exists():
            entry["weights_sha256"] = hashlib.sha256(weights_file.read_bytes()).hexdigest()
            if weights:
                bundle.add_file(weights_file, f"{prefix}models/{model_dir.name}/model.pt")
            else:
                result.notes.append(f"{model_dir.name}: weights not included "
                                    "(use --weights); their hash is in the manifest")
        found.append(entry)
    return found


README = """\
# Fungus-CV bundle

Everything needed to reproduce this result: settings, annotations, frames excluded by hand,
SAM prompts, measurements, reports and model cards.

- `manifest.json` lists every file with its SHA-256 hash, every photo's hash (whether or not
  the photos are in this bundle), and the exact package versions used.
- Check the bundle with `fungus archive --verify <this file>`.
- Photos are only here if the bundle was made with `--frames`; masks and overlays are left
  out because `fungus analyze` recreates them from the settings in `config.yaml`.

## Reproducing

1. Install the same versions: see `manifest.json` -> `environment.packages`
   (`fungus_cv_version` and `git_commit` say which code produced it).
2. Put the photos back in `frames/` (their hashes are in the manifest).
3. `fungus analyze <folder>` then `fungus report <folder>`, or `fungus study <study.yaml>`.
"""


def build(target: Path, out: Path, frames: bool = False, masks: bool = False,
          weights: bool = False) -> ArchiveResult:
    """Bundle an experiment folder, or a study file with all of its replicates."""
    target, out = Path(target), Path(out)
    result = ArchiveResult(path=out)
    out.parent.mkdir(parents=True, exist_ok=True)
    manifest = {"format": BUNDLE_FORMAT, "created_utc": iso_utc(utc_now()),
                "environment": environment()}

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        bundle = _Bundle(zf)
        if target.is_dir():
            experiment = Experiment(target)
            manifest["kind"] = "experiment"
            manifest["experiment"] = _add_experiment(bundle, experiment, "", frames, masks,
                                                     weights, result)
        else:
            from fungus_cv.analyze.study import load_study

            study = load_study(target)
            manifest["kind"] = "study"
            manifest["study"] = {"file": target.name, "name": study.name}
            bundle.add_file(target, target.name)
            baseline = target.parent / "baseline.json"
            if baseline.exists():
                bundle.add_file(baseline, baseline.name)
            results_dir = target.parent / f"{target.stem}_results"
            for path in sorted(results_dir.rglob("*")) if results_dir.is_dir() else []:
                if path.is_file():
                    bundle.add_file(path, path.relative_to(target.parent).as_posix())
            experiments = []
            for spec in study.experiments:
                root = (target.parent / spec.path).resolve()
                try:
                    experiment = Experiment(root)
                except (FileNotFoundError, ValueError) as exc:
                    result.notes.append(f"{spec.path}: not bundled ({exc})")
                    continue
                prefix = f"experiments/{Path(spec.path).name}/"
                entry = _add_experiment(bundle, experiment, prefix, frames, masks, weights,
                                        result)
                experiments.append({"condition": spec.condition, "replicate": spec.replicate,
                                    "prefix": prefix, **entry})
            manifest["study"]["experiments"] = experiments

        manifest["notes"] = result.notes
        bundle.add_text(README, "README.md")
        manifest["files"] = bundle.entries
        zf.writestr(MANIFEST_NAME, json.dumps(manifest, indent=2))
    result.files = len(bundle.entries) + 1
    result.bytes_stored = out.stat().st_size
    return result


@dataclass
class Check:
    ok: bool
    files: int = 0
    changed: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)
    extra: list[str] = field(default_factory=list)
    manifest: dict = field(default_factory=dict)


def verify(bundle_path: Path) -> Check:
    """Re-hash every file in a bundle and compare with its manifest."""
    with zipfile.ZipFile(Path(bundle_path)) as zf:
        names = set(zf.namelist())
        if MANIFEST_NAME not in names:
            raise ValueError(f"{bundle_path} has no {MANIFEST_NAME}: not a Fungus-CV bundle")
        manifest = json.loads(zf.read(MANIFEST_NAME))
        listed = {e["path"]: e for e in manifest.get("files", [])}
        check = Check(ok=True, files=len(listed), manifest=manifest)
        for name, entry in listed.items():
            if name not in names:
                check.missing.append(name)
                continue
            data = zf.read(name)
            if hashlib.sha256(data).hexdigest() != entry["sha256"]:
                check.changed.append(name)
        check.extra = sorted(names - set(listed) - {MANIFEST_NAME})
    check.ok = not (check.changed or check.missing)
    return check
