"""Build the standalone Fungus-CV app with PyInstaller.

    python packaging/build_app.py              # app without PyTorch (color methods only)
    python packaging/build_app.py --with-models  # also bundle PyTorch/SAM (much larger)

Output: dist/Fungus-CV.app (macOS), dist/Fungus-CV/Fungus-CV.exe (Windows),
dist/Fungus-CV/Fungus-CV (Linux).
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGING = ROOT / "packaging"
sys.path.insert(0, str(ROOT / "src"))

from fungus_cv import __version__  # noqa: E402

BUNDLE_ID = "org.fungus-cv.app"
CAMERA_REASON = ("Fungus-CV uses the camera to take time-lapse photos of your experiments "
                 "and to show a live preview for framing and focus.")
MODEL_PACKAGES = ["torch", "torchvision", "transformers", "accelerate", "safetensors",
                  "tokenizers", "huggingface_hub"]


def spec(with_models: bool) -> str:
    icon_mac = PACKAGING / "build" / "icon.icns"
    icon_win = PACKAGING / "build" / "icon.ico"
    excludes = [] if with_models else MODEL_PACKAGES
    hidden = ["fungus_cv.gui.pages." + m for m in
              ("analyze", "camera", "capture", "doctor", "experiment", "labels", "prompt",
               "report", "setup", "study", "train", "validation")]
    hidden += ["scipy.optimize", "scipy.signal", "scipy.spatial", "scipy.sparse.csgraph",
               "scipy.stats",
               "matplotlib.backends.backend_agg"]
    if sys.platform == "darwin":
        hidden += ["AVFoundation", "Foundation"]
    return f'''# Generated by packaging/build_app.py
from PyInstaller.utils.hooks import collect_submodules
a = Analysis(
    [{str(PACKAGING / "fungus_cv_app.py")!r}],
    pathex=[{str(ROOT / "src")!r}],
    hiddenimports={hidden!r} + collect_submodules("fungus_cv"),
    excludes={excludes!r} + ["tkinter", "PyQt5", "PyQt6", "IPython", "pytest"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name="Fungus-CV", console=False,
          icon={str(icon_win if sys.platform.startswith("win") else icon_mac)!r}
          if {sys.platform != "linux"!r} else None,
          codesign_identity=None, entitlements_file=None)
coll = COLLECT(exe, a.binaries, a.datas, name="Fungus-CV")
app = BUNDLE(
    coll,
    name="Fungus-CV.app",
    icon={str(icon_mac)!r},
    bundle_identifier={BUNDLE_ID!r},
    version={__version__!r},
    info_plist={{
        "CFBundleName": "Fungus-CV",
        "CFBundleDisplayName": "Fungus-CV",
        "CFBundleShortVersionString": {__version__!r},
        "NSCameraUsageDescription": {CAMERA_REASON!r},
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "12.0",
    }},
)
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--with-models", action="store_true",
                        help="bundle PyTorch/transformers for SAM 2 and trained models")
    args = parser.parse_args()
    if args.with_models:
        # PyInstaller bundles what it can import: without these the build quietly produces an
        # app whose SAM prompts and model-based analysis fail at runtime.
        missing = [p for p in ("torch", "torchvision", "transformers")
                   if importlib.util.find_spec(p) is None]
        if missing:
            sys.exit(f"--with-models needs {', '.join(missing)} in this environment: "
                     'pip install -e ".[sam]" (with an NVIDIA GPU, install the CUDA build of '
                     "torch first)")

    subprocess.run([sys.executable, str(PACKAGING / "make_icon.py")], check=True)
    spec_path = PACKAGING / "build" / "Fungus-CV.spec"
    spec_path.write_text(spec(args.with_models), encoding="utf-8")
    subprocess.run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
                    "--distpath", str(ROOT / "dist"), "--workpath",
                    str(PACKAGING / "build" / "work"), str(spec_path)], check=True)

    if sys.platform == "darwin":
        app = ROOT / "dist" / "Fungus-CV.app"
        # Ad-hoc signature: macOS needs a stable code identity to remember the camera
        # permission. Distribute with a Developer ID signature + notarization instead.
        subprocess.run(["codesign", "--force", "--deep", "--sign", "-", str(app)], check=True)
        shutil.rmtree(ROOT / "dist" / "Fungus-CV", ignore_errors=True)
        print(f"\nBuilt {app}\nOpen it with:  open {app}")
    else:
        print(f"\nBuilt {ROOT / 'dist' / 'Fungus-CV'}")


if __name__ == "__main__":
    main()
